version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=example
    ports: 
      - 6379:6379
