"""create table salt

Revision ID: 2b70512b6902
Revises: d1b120307aac
Create Date: 2023-03-21 10:45:40.866325

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "2b70512b6902"
down_revision = "d1b120307aac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=True
        ),
        sa.Column("salt", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_salt_email"), "salt", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_salt_email"), table_name="salt")
    op.drop_table("salt")
    # ### end Alembic commands ###
